highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://wojciech-szymanski.github.io/
author: Wojciech Szymanski
sass:
  sass_dir: _sass
  style: compressed

# edit this section with your information
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Wojciech Szymanski - Web Developer based in London
description: I specialise in JavaScript and my favourite framework of choice is Angular. I like working with Node and MongoDB as well
name: Wojciech Szymanski
email: me@wszymanski.com
email_full: mailto:me@wszymanski.com
email_left: me
email_right: wszymanski.com
website: wszymanski.com
website_full: https://wszymanski.com/
github: wojciech-szymanski
linkedin: wojciech-szymański-75b12529
tel: +44 7487 633866
google_maps: 'https://www.google.co.uk/maps/place/16+Carlton+Drive,+London,+SW15+2BD'
postcode: SW15 2BD
city: London
country: United Kingdom
google_analytics: UA-72480040-1

# needed for travis-ci build
exclude: [vendor]
